In [5]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
import pickle
import pandas as pd 
from sklearn.model_selection import train_test_split

In [6]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [8]:
##encode the categotical result
label_encoder_gender=LabelEncoder()

data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [9]:
##Similar for the geography column
onehot_encoder_geo=OneHotEncoder()
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [11]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
data.describe()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,650.528800,0.545700,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700,0.501400,0.250900,0.247700
std,96.653299,0.497932,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769,0.500023,0.433553,0.431698
min,350.000000,0.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,0.000000,0.000000,0.000000
25%,584.000000,0.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,0.000000,0.000000,0.000000
50%,652.000000,1.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,1.000000,0.000000,0.000000
75%,718.000000,1.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,1.000000,1.000000,0.000000
max,850.000000,1.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,1.000000,1.000000,1.000000

In [13]:
x=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [16]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem Statement

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From c:\Users\Lenovo\Desktop\PROJECT ANN\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [18]:
## Build the model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) ###output layer for regression (By the default the activation function is linear)
     
])

#### Compile the model
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mae'])    ###mae stands for Mean Absolute Error.

model.summary()

WARNING:tensorflow:From c:\Users\Lenovo\Desktop\PROJECT ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\Users\Lenovo\Desktop\PROJECT ANN\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
## set up TensorBoard
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [20]:
#### Set up Early stopping 
early_stopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [21]:
### Train the model
history=model.fit(
    X_train,Y_train,
    validation_data=(X_test,Y_test),
    epochs=100,
    callbacks=[early_stopping,tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Lenovo\Desktop\PROJECT ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Lenovo\Desktop\PROJECT ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 6ms/step - loss: 13383834624.0000 - mae: 100377.5781 - val_loss: 13008147456.0000 - val_mae: 98523.6250
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 13238080512.0000 - mae: 99652.4844 - val_loss: 12718636032.0000 - val_mae: 97059.8594
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 12721883136.0000 - mae: 97100.7344 - val_loss: 11975593984.0000 - val_mae: 93296.6875
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 11696830464.0000 - mae: 92035.4062 - val_loss: 10723742720.0000 - val_mae: 86970.1875
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 10192413696.0000 - mae: 84549.7578 - val_loss: 9082167296.0000 - val_mae: 78678.5391
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 8408548864.0000 - mae: 75642.2344 - val_loss: 7311174144.0000 - val_mae: 69821.3203
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 6645534208.0000 - mae: 66674.0859 - val_loss: 5732118528.0000 - val_mae: 61937.4531
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 5202612224.0000 - mae: 59384.7266 - val_loss: 4583281152.0000 - val_mae: 56191.5000
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 4241274112.0000 - mae: 54376.5859 - val_loss: 3918027008.0000 - val_mae: 52750.6992
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 3732473600.0000 - mae: 51720.3867 - val_loss: 3622215168.0000 - val_mae: 51283.6484
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 3516553984.0000 - mae: 50590.5117 - val_loss: 3518942976.0000 - val_mae: 50847.6211
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 3437523200.0000 - mae: 50194.6914 - val_loss: 3483636480.0000 - val_mae: 50689.6914
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 3407456512.0000 - mae: 50067.3281 - val_loss: 3467185152.0000 - val_mae: 50622.2539
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 3390908672.0000 - mae: 49980.7891 - val_loss: 3454852864.0000 - val_mae: 50569.1523
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 3379135744.0000 - mae: 49923.6797 - val_loss: 3444827904.0000 - val_mae: 50529.0664
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 3370113536.0000 - mae: 49884.4727 - val_loss: 3436834304.0000 - val_mae: 50493.3984
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 3362160640.0000 - mae: 49838.5430 - val_loss: 3429050624.0000 - val_mae: 50460.9570
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 3355810816.0000 - mae: 49806.5156 - val_loss: 3422376192.0000 - val_mae: 50425.2227
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 3349801984.0000 - mae: 49777.7344 - val_loss: 3414601216.0000 - val_mae: 50384.6641
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 3345158656.0000 - mae: 49753.9727 - val_loss: 3409605888.0000 - val_mae: 50362.9648
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 3340657408.0000 - mae: 49726.6992 - val_loss: 3405246208.0000 - val_mae: 50339.3555
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 3336968960.0000 - mae: 49706.6836 - val_loss: 3402353920.0000 - val_mae: 50330.8906
Epoch 23/100
250/250 [==============================] - 1s 4ms/step - loss: 3333672704.0000 - mae: 49690.8438 - val_loss: 3396732416.0000 - val_mae: 50298.3750
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 3330014720.0000 - mae: 49663.9883 - val_loss: 3396461312.0000 - val_mae: 50306.8086
Epoch 25/100
250/250 [==============================] - 1s 4ms/step - loss: 3327786752.0000 - mae: 49656.7227 - val_loss: 3391980544.0000 - val_mae: 50280.8281
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 3325276672.0000 - mae: 49643.6953 - val_loss: 3389786624.0000 - val_mae: 50273.9023
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 3322949120.0000 - mae: 49629.7383 - val_loss: 3387061504.0000 - val_mae: 50263.2969
Epoch 28/100
250/250 [==============================] - 1s 2ms/step - loss: 3320708608.0000 - mae: 49616.4727 - val_loss: 3385054976.0000 - val_mae: 50255.8008
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 3319013376.0000 - mae: 49602.0430 - val_loss: 3382684160.0000 - val_mae: 50243.6641
Epoch 30/100
250/250 [==============================] - 1s 4ms/step - loss: 3317299712.0000 - mae: 49598.3711 - val_loss: 3379761920.0000 - val_mae: 50225.0898
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 3315841792.0000 - mae: 49584.6562 - val_loss: 3380577536.0000 - val_mae: 50237.4570
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 3314429440.0000 - mae: 49579.6680 - val_loss: 3378803456.0000 - val_mae: 50231.7773
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 3312685824.0000 - mae: 49567.6641 - val_loss: 3377411840.0000 - val_mae: 50226.3359
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 3311557376.0000 - mae: 49558.1602 - val_loss: 3377726720.0000 - val_mae: 50230.6328
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 3310290688.0000 - mae: 49552.9531 - val_loss: 3375923456.0000 - val_mae: 50221.2812
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 3309106944.0000 - mae: 49541.3750 - val_loss: 3373956352.0000 - val_mae: 50210.3750
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 3308081920.0000 - mae: 49535.7461 - val_loss: 3373978368.0000 - val_mae: 50212.3945
Epoch 38/100
250/250 [==============================] - 1s 4ms/step - loss: 3307237632.0000 - mae: 49529.3984 - val_loss: 3373736192.0000 - val_mae: 50214.5742
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 3306167040.0000 - mae: 49523.0977 - val_loss: 3373065216.0000 - val_mae: 50212.2070
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 3305632512.0000 - mae: 49517.1914 - val_loss: 3370294528.0000 - val_mae: 50194.3047
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 3304115968.0000 - mae: 49507.0000 - val_loss: 3371693824.0000 - val_mae: 50204.1289
Epoch 42/100
250/250 [==============================] - 1s 2ms/step - loss: 3303524352.0000 - mae: 49501.3672 - val_loss: 3370112768.0000 - val_mae: 50193.2148
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 3302971136.0000 - mae: 49501.5781 - val_loss: 3369287168.0000 - val_mae: 50188.2148
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 3301996288.0000 - mae: 49493.8477 - val_loss: 3370062848.0000 - val_mae: 50195.6172
Epoch 45/100
250/250 [==============================] - 1s 4ms/step - loss: 3301446400.0000 - mae: 49491.8984 - val_loss: 3369084416.0000 - val_mae: 50189.4531
Epoch 46/100
250/250 [==============================] - 1s 4ms/step - loss: 3300410112.0000 - mae: 49479.4375 - val_loss: 3369026048.0000 - val_mae: 50190.6055
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 3299757568.0000 - mae: 49474.2695 - val_loss: 3369892352.0000 - val_mae: 50196.2656
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 3299230208.0000 - mae: 49477.2070 - val_loss: 3369174784.0000 - val_mae: 50194.8203
Epoch 49/100
250/250 [==============================] - 1s 2ms/step - loss: 3298892032.0000 - mae: 49467.7461 - val_loss: 3368959232.0000 - val_mae: 50194.5156
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 3297949696.0000 - mae: 49462.5547 - val_loss: 3368271616.0000 - val_mae: 50191.0195
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 3297459200.0000 - mae: 49461.1758 - val_loss: 3367116032.0000 - val_mae: 50181.8516
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 3296806656.0000 - mae: 49452.3750 - val_loss: 3367960832.0000 - val_mae: 50189.9609
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 3296240128.0000 - mae: 49451.6875 - val_loss: 3366620416.0000 - val_mae: 50177.0664
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 3295770112.0000 - mae: 49449.9961 - val_loss: 3365843968.0000 - val_mae: 50172.8516
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 3295969280.0000 - mae: 49451.4023 - val_loss: 3367320832.0000 - val_mae: 50183.9219
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 3294731776.0000 - mae: 49444.4492 - val_loss: 3367816192.0000 - val_mae: 50187.2344
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 3294253056.0000 - mae: 49435.9961 - val_loss: 3366606848.0000 - val_mae: 50179.6719
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 3294085376.0000 - mae: 49435.2930 - val_loss: 3366158848.0000 - val_mae: 50177.7812
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 3293614592.0000 - mae: 49432.7461 - val_loss: 3365000448.0000 - val_mae: 50167.9883
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 3292696064.0000 - mae: 49422.6875 - val_loss: 3365816832.0000 - val_mae: 50174.7148
Epoch 61/100
250/250 [==============================] - 1s 4ms/step - loss: 3292580608.0000 - mae: 49424.6094 - val_loss: 3366136320.0000 - val_mae: 50179.1719
Epoch 62/100
250/250 [==============================] - 1s 4ms/step - loss: 3291773696.0000 - mae: 49418.2656 - val_loss: 3367702528.0000 - val_mae: 50188.0703
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 3291719936.0000 - mae: 49420.0117 - val_loss: 3366822144.0000 - val_mae: 50183.7656
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 3291077120.0000 - mae: 49414.2812 - val_loss: 3366596096.0000 - val_mae: 50181.2891

In [22]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [26]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 16932), started 0:02:29 ago. (Use '!kill 16932' to kill it.)

In [24]:
"""conda activate venv
pip install --upgrade setuptools"""

'conda activate venv\npip install --upgrade setuptools'

In [27]:
### Evaluate the model
test_loss,test_mae=model.evaluate(X_test,Y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 [==============================] - 4s 21ms/step - loss: 3365000448.0000 - mae: 50167.9883
Test Loss: 3365000448.0, Test MAE: 50167.98828125

In [28]:
model.save('regression_model.h5')

c:\Users\Lenovo\Desktop\PROJECT ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(